[package]
name = "ffrostfall/crunchyroll"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	".github",
	".lune",
	".vscode",
	"tests",
	"types",
	"vendor",
	".gitattributes",
	".gitignore",
	".styluaignore",
	"README.md",
	"roblox-tests.project.json",
	"rokit.toml",
	"sourcemap.json",
	"stylua.toml",
	"build",
	"build.rbxl",
	"build.rbxl.lock",
	"crunchyroll.rbxm",
	"docs",
]
